export const userTypes = {
  USR_LOGIN_USER: "USR/LOGIN_USER",
  USR_LOGIN_USER_PENDING: "USR/LOGIN_USER_PENDING",
  USR_LOGIN_USER_REJECTED: "USR/LOGIN_USER_REJECTED",
  USR_LOGIN_USER_FULFILLED: "USR/LOGIN_USER_FULFILLED",

  USER_LOGIN_ADMIN: "USR/LOGIN_ADMIN",
  USER_LOGIN_ADMIN_PENDING: "USR/LOGIN_ADMIN_PENDING",
  USER_LOGIN_ADMIN_REJECTED: "USR/LOGIN_ADMIN_REJECTED",
  USER_LOGIN_ADMIN_FULFILLED: "USR/LOGIN_ADMIN_FULFILLED",

  USR_LOGOUT_USER: "USR/LOGOUT_USER",
  USR_LOGOUT_USER_PENDING: "USR/LOGOUT_USER_PENDING",
  USR_LOGOUT_USER_REJECTED: "USR/LOGOUT_USER_REJECTED",
  USR_LOGOUT_USER_FULFILLED: "USR/LOGOUT_USER_FULFILLED",

  USR_VALIDATE_USER: "USR/VALIDATE_USER",
  USR_VALIDATE_USER_PENDING: "USR/VALIDATE_USER_PENDING",
  USR_VALIDATE_USER_REJECTED: "USR/VALIDATE_USER_REJECTED",
  USR_VALIDATE_USER_FULFILLED: "USR/VALIDATE_USER_FULFILLED",

  USR_UPDATE_USER: "USR/UPDATE_USER",
  USR_UPDATE_USER_PENDING: "USR/UPDATE_USER_PENDING",
  USR_UPDATE_USER_REJECTED: "USR/UPDATE_USER_REJECTED",
  USR_UPDATE_USER_FULFILLED: "USR/UPDATE_USER_FULFILLED",

  USR_REGISTER_USER: "USR/REGISTER_USER",
  USR_REGISTER_USER_PENDING: "USR/REGISTER_USER_PENDING",
  USR_REGISTER_USER_REJECTED: "USR/REGISTER_USER_REJECTED",
  USR_REGISTER_USER_FULFILLED: "USR/REGISTER_USER_FULFILLED",

  USR_UPDATE_USER_PASSWORD: "USR/UPDATE_USER_PASSWORD",
  USR_UPDATE_USER_PASSWORD_PENDING: "USR/UPDATE_USER_PASSWORD_PENDING",
  USR_UPDATE_USER_PASSWORD_REJECTED: "USR/UPDATE_USER_PASSWORD_REJECTED",
  USR_UPDATE_USER_PASSWORD_FULFILLED: "USR/UPDATE_USER_PASSWORD_FULFILLED",

  USR_SELECT_USER: "USR/SELECT_USER",
  USR_SELECT_USER_PENDING: "USR/SELECT_USER_PENDING",
  USR_SELECT_USER_REJECTED: "USR/SELECT_USER_REJECTED",
  USR_SELECT_USER_FULFILLED: "USR/SELECT_USER_FULFILLED",

  USR_REGISTER_ORCID_USER: "USR/REGISTER_ORCID_USER",
  USR_REGISTER_ORCID_USER_PENDING: "USR/REGISTER_ORCID_USER_PENDING",
  USR_REGISTER_ORCID_USER_REJECTED: "USR/REGISTER_ORCID_USER_REJECTED",
  USR_REGISTER_ORCID_USER_FULFILLED: "USR/REGISTER_ORCID_USER_FULFILLED",

  USR_CLEAR_USER: "USR/CLEAR_USER",
};

export type User = {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  full_name: string;
  created_at: string;
  updated_at: string;
};

export type Admin = {
  id: number;
  email: string;
  role: number;
  created_at: string;
  updated_at: string;
};

export type LoginCredentials = {
  email: string;
  password: string;
  domain: string;
};

export type UserState = {
  profile: User | null;
  currentAdmin: Admin | null;
  selectedUser: User | null;
  orcidAccount: any;
};
