export const types = {
  WLT_BUILD_FILL_TREASURY: "WLT_FILL_TREASURY",
  WLT_BUILD_FILL_TREASURY_FULFILLED: "WLT_FILL_TREASURY_FULFILLED",
  WLT_BUILD_FILL_TREASURY_REJECTED: "WLT_FILL_TREASURY_REJECTED",
  WLT_BUILD_FILL_TREASURY_PENDING: "WLT_FILL_TREASURY_PENDING",

  WLT_BUILD_SPEND_TREASURY: "WLT_SPEND_TREASURY",
  WLT_BUILD_SPEND_TREASURY_FULFILLED: "WLT_SPEND_TREASURY_FULFILLED",
  WLT_BUILD_SPEND_TREASURY_REJECTED: "WLT_SPEND_TREASURY_REJECTED",
  WLT_BUILD_SPEND_TREASURY_PENDING: "WLT_SPEND_TREASURY_PENDING",

  WLT_SIGN_MESSAGE: "WLT_SIGN_MESSAGE",
  WLT_CLEAR_TX: "WLT_CLEAR_TX",

  WLT_SUBMIT_FILL_TREASURY: "WLT_SUBMIT_MESSAGE",
  WLT_SUBMIT_FILL_TREASURY_FULFILLED: "WLT_SUBMIT_MESSAGE_FULFILLED",
  WLT_SUBMIT_FILL_TREASURY_REJECTED: "WLT_SUBMIT_MESSAGE_REJECTED",
  WLT_SUBMIT_FILL_TREASURY_PENDING: "WLT_SUBMIT_MESSAGE_PENDING",

  WLT_SUBMIT_SPEND_TREASURY: "WLT_SUBMIT_SPEND_TREASURY",
  WLT_SUBMIT_SPEND_TREASURY_FULFILLED: "WLT_SUBMIT_SPEND_TREASURY_FULFILLED",
  WLT_SUBMIT_SPEND_TREASURY_REJECTED: "WLT_SUBMIT_SPEND_TREASURY_REJECTED",
  WLT_SUBMIT_SPEND_TREASURY_PENDING: "WLT_SUBMIT_SPEND_TREASURY_PENDING",

  WLT_FETCH_WALLET: "WLT_FETCH_WALLET",
  WLT_FETCH_WALLET_FULFILLED: "WLT_FETCH_WALLET_FULFILLED",
  WLT_FETCH_WALLET_REJECTED: "WLT_FETCH_WALLET_REJECTED",
  WLT_FETCH_WALLET_PENDING: "WLT_FETCH_WALLET_PENDING",
};

export type WalletState = {
  tx_id: string;
  signature: string;
  tx_id_fulfilled: string;
  treasury: Treasury | null;
  witness_set: any;
};

export type TreasuryStatus =
  | "treasury_empty"
  | "no_treasury"
  | "treasury_found"
  | "error";

export type Treasury = {
  status: TreasuryStatus;
  utxos?: Array<any>;
  balance?: number;
  address?: string;
};
